owner: hantswilliams # GitHub username

repo: upptime # GitHub repository name

user-agent: hantswilliams

sites: # List of endpoints to track
  - name: SDoH Stony Brook Hospital 
    url: https://sdoh.ahi-projects.com/

assignees: # Users to assign downtime issues (optional)
  - hantswilliams

status-website:
  name: Status
  cname: status.appliedhealthinformatics.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */2 * * *" # checks sites once every other hour 



