owner: hantswilliams # GitHub username

repo: upptime # GitHub repository name

user-agent: hantswilliams

sites: # List of endpoints to track
  - name: SBHS - Falls Prevention
    url: https://longislandfallsfree.com/
  - name: SBHS - SDoH
    url: https://sdoh.ahi-projects.com/
  - name: SBHS - Smoking API, NY state
    url: https://ny-smoke-api.ahi-projects.com/
  - name: SHP - PA Program Analytics
    url: https://pa-program.appliedhealthinformatics.com/
  - name: SHP - QR Code Generator 
    url: https://qrcode.appliedhealthinformatics.com/ 
  - name: SHP-AHI Book - Data Science for Health Informatics 
    url: https://book.datascience.appliedhealthinformatics.com/ 
  - name: SHP-AHI Resume Builder 
    url: https://resume.appliedhealthinformatics.com/ 
  - name: SHP-AHI Blog 
    url: https://blog.appliedhealthinformatics.com/ 
  - name: SHP-AHI-Research - Project Discover 
    url: https://discover.appliedhealthinformatics.com/
  - name: SHP-AHI-Research - ClinicalTrials.gov Exploration
    url: https://trials.appliedhealthinformatics.com/ 

assignees: # Users to assign downtime issues (optional)
  - hantswilliams

status-website:
  name: Status
  cname: status.appliedhealthinformatics.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */2 * * *" # checks sites once every other hour 



